name: "Instance Update Action"
description: "Used to update the settings of existing cluster instances"
branding:
  color: "blue"
  icon: "cloud-rain"
inputs:
  spheron-token:
    description: "A spheron token for the compute organization"
    required: true
  instance-id:
    description: "The ID of the cluster instance"
    required: true
  tag:
    description: "The tag of the Docker image to run"
    required: false
    default: "latest"
  env:
    description: "Environment variables. Format: [ 'key1=value1' , 'key2=value2', ...]"
    required: false
  secret-env:
    description: "Secret environment variables. Format: ['key1=value1', 'key2=value2', ...]"
    required: false
outputs:
  cluster-id:
    description: "The cluster ID of the updated instance"
  instance-id:
    description: "The updated cluster instance ID"
  deployment-id:
    description: "The deployment ID of the updated instance"
  organization-id:
    description: "The organization ID of the updated instance"
runs:
  using: "node16"
  main: "index.js"
